server:
  port: 8878
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application: 
    name: 'news-edit-ms'
  datasource:
    username: root
    password: root
    url: 'jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=UTF-8'
    type: com.alibaba.druid.pool.DruidDataSource 

pagehelper:
  helper-dialect: mysql
  reasonable: true

 